# Import libraries

In [41]:
from pathlib import Path
import pandas as pd
import json
import re

# Logging Setup

In [42]:
# Current working directory
BASE_PATH = Path.cwd().parent

DATA_PATH = BASE_PATH / "data" / "raw"/ "app_logs_7days.jsonl"
QUARANTINE_PATH = BASE_PATH / "notebooks" / "outputs" / "malformed_records.jsonl"

# Data Loading

Here I used **Lazy file streaming**. Why I think that's matter: 
- Python processes this log file sequentially line-by-line rather than loading an entire file into RAM
- This ensures memory usage stays contanst O(1), no matter the size of our `.jsonl` file

In [43]:
success_count = 0
error_count = 0
valid_records = []

with open(DATA_PATH, mode="r", encoding="utf-8") as f_in, \
	open(QUARANTINE_PATH, mode="w", encoding="utf-8") as f_err: # overwrite mode
		# Stream line-by-line
		for line_num, line in enumerate(f_in, start=1):
			raw_line = line.strip() # <class 'str'>
		   
			if not raw_line:
				continue 
			
			try:
				record = json.loads(raw_line) # <class 'dict'>
				success_count += 1
				valid_records.append(record)
			
			except json.JSONDecodeError as e:
				error_count += 1
				
				malformed_record = {
					"source_file": str(DATA_PATH),
					"line_number": line_num,
					"raw_line": raw_line,
					"error_message": str(e)
				}
				f_err.write(json.dumps(malformed_record) + "\n")

# EDA

In [44]:
df = pd.DataFrame(valid_records)
del valid_records

In [45]:
df.head()

,timestamp,service,level,message,request_id,trace_id
0,2026-07-27T00:02:47Z,notification-worker,ERROR,ERR SMTPConnRefused host=mail-gw,req-65568711,NaN
1,2026-07-27T00:12:06Z,auth-service,INFO,Session created uid=u2746,req-72350830,NaN
2,2026-07-27T00:13:20Z,payment-api,WARN,Retry 1/3 calling notification-worker,req-22315507,NaN
3,2026-07-27T00:20:17Z,notification-worker,INFO,SMS sent uid=u1132,req-27740248,NaN
4,2026-07-27T00:27:38Z,auth-service,WARN,Slow login 900ms uid=u7882,req-95306788,NaN

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2905 entries, 0 to 2904
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   timestamp   2905 non-null   str
 1   service     2905 non-null   str
 2   level       2887 non-null   str
 3   message     2905 non-null   str
 4   request_id  2905 non-null   str
 5   trace_id    1199 non-null   str
dtypes: str(6)
memory usage: 136.3 KB

In [47]:
non_null_counts = df.notnull().sum()
null_counts = df.isnull().sum()
null_percentage = (null_counts / len(df)) * 100

summary_df = pd.DataFrame({
	"Non-null Count": non_null_counts,
	"Null Count": null_counts,
	"Null Percentage (%)": null_percentage.round(2)
})

print(summary_df)

            Non-null Count  Null Count  Null Percentage (%)
timestamp             2905           0                 0.00
service               2905           0                 0.00
level                 2887          18                 0.62
message               2905           0                 0.00
request_id            2905           0                 0.00
trace_id              1199        1706                58.73

**Exact Row Duplicates** occured

In [48]:
duplicated_df = df[df.duplicated(keep='first')]

display(duplicated_df)
print(len(duplicated_df), "duplicated records found.")

,timestamp,service,level,message,request_id,trace_id
57,2026-07-27T03:51:26Z,batch-report,WARN,Report row mismatch expected=1061 got=1082,req-84892608,NaN
90,2026-07-27T05:52:54Z,auth-service,INFO,Token refreshed uid=u9837,req-25014631,NaN
209,2026-07-27T12:48:15Z,notification-worker,INFO,Email sent uid=u3328,req-33562830,NaN
321,2026-07-27T19:44:26Z,auth-service,INFO,Session created uid=u1998,req-77491435,NaN
372,2026-07-27T22:23:19Z,batch-report,INFO,Daily report job finished rows=851,req-69920305,NaN
474,2026-07-28T04:54:18Z,payment-api,INFO,Payment processed txn=t141094 amount=120000,req-79342339,NaN
535,2026-07-28T10:14:59Z,auth-service,INFO,Token refreshed uid=u5872,req-75893962,NaN
766,2026-07-28T23:38:39Z,batch-report,INFO,Daily report job finished rows=1163,req-75050252,NaN
824,2026-07-29T01:39:57Z,batch-report,INFO,Daily report job finished rows=1110,req-92220752,NaN
842,2026-07-29T02:44:06Z,notification-worker,INFO,Email sent uid=u7013,req-66736822,NaN
1012,2026-07-29T14:31:19Z,payment-api,INFO,Payment processed txn=t286657 amount=120000,req-37947183,NaN
1017,2026-07-29T14:53:01Z,batch-report,INFO,Daily report job finished rows=885,req-21503407,NaN
1080,2026-07-29T18:17:58Z,batch-report,INFO,Daily report job started,req-35754346,NaN
1184,2026-07-30T03:25:37+07:00,web-portal,INFO,Request completed path=/report in 237ms,req-17096679,NaN
1391,2026-07-30T09:47:55Z,notification-worker,INFO,SMS sent uid=u1871,req-32997024,NaN
1510,2026-07-30T15:51:10Z,payment-api,ERROR,ERR ConnTimeout db-primary after 30s retry=3,req-66918776,NaN
1532,2026-07-30T17:00:16Z,payment-api,INFO,Balance check ok uid=u9123,req-47726289,NaN
1754,2026-07-31T02:11:57Z,auth-service,INFO,Token refreshed uid=u8046,req-52734662,trace-9872881926
1915,2026-07-31T13:13:16+07:00,web-portal,WARN,Response time 2100ms path=/report,req-42576819,trace-9072159605
1926,2026-07-31T13:55:22+07:00,web-portal,INFO,Request completed path=/home in 802ms,req-84820714,trace-8605695669
1994,2026-07-31T17:43:22Z,payment-api,INFO,Balance check ok uid=u7541,req-65807734,trace-5121529498
2050,2026-07-31T21:43:41+07:00,web-portal,INFO,Request completed path=/home in 315ms,req-66401535,trace-7894521683
2424,2026-08-01T20:55:03Z,auth-service,INFO,Session created uid=u1295,req-55925432,trace-7055941464
2603,2026-08-02T07:07:32+07:00,web-portal,INFO,Request completed path=/report in 93ms,req-54970734,trace-7933634881
2614,2026-08-02T07:50:24Z,payment-api,INFO,Payment processed txn=t888000 amount=990000,req-76495786,trace-6099376282
2660,2026-08-02T09:24:37Z,payment-api,INFO,Balance check ok uid=u9691,req-47303947,trace-9823166334
2797,2026-08-02T18:31:51Z,payment-api,INFO,Payment processed txn=t805590 amount=120000,req-66194219,trace-8311872268
2888,2026-08-03T02:19:53+07:00,web-portal,INFO,Request completed path=/report in 405ms,req-57365466,trace-6391704367

28 duplicated records found.

In [49]:
df_cleaned = df.drop_duplicates(keep='first')

## 1. timestamp

In [50]:
def detect_ts_format(x):
    x = str(x)

    if re.fullmatch(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z", x):
        return "UTC_Z"                     # 2026-07-27T08:30:00Z

    elif re.fullmatch(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[+-]\d{2}:\d{2}", x):
        return "ISO_timezone_offset"        # 2026-07-27T07:58:15+07:00

    elif re.fullmatch(r"\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}", x):
        return "datetime_space"             # 2026-07-27 08:30:00

    elif re.fullmatch(r"\d{4}-\d{2}-\d{2}", x):
        return "date_only"                  # 2026-07-27

    else:
        return "unknown/invalid"

df_cleaned["timestamp_format"] = df_cleaned["timestamp"].apply(detect_ts_format)

print(df_cleaned["timestamp_format"].value_counts())

timestamp_format
UTC_Z                  2267
ISO_timezone_offset     590
unknown/invalid          20
Name: count, dtype: int64

In [51]:
df_cleaned[df_cleaned['timestamp_format'] == 'unknown/invalid']

,timestamp,service,level,message,request_id,trace_id,timestamp_format
33,not-a-date,auth-service,WARN,Clock sync failed,req-32170750,NaN,unknown/invalid
228,not-a-date,auth-service,WARN,Clock sync failed,req-80542438,trace-2840524582,unknown/invalid
483,not-a-date,auth-service,WARN,Clock sync failed,req-64770806,trace-3597287435,unknown/invalid
502,not-a-date,batch-report,WARN,Clock sync failed,req-89141563,trace-1842573576,unknown/invalid
553,not-a-date,notification-worker,WARN,Clock sync failed,req-95756894,trace-1839947796,unknown/invalid
696,not-a-date,payment-api,WARN,Clock sync failed,req-46941691,NaN,unknown/invalid
1029,not-a-date,batch-report,WARN,Clock sync failed,req-58571652,trace-8069263805,unknown/invalid
1191,not-a-date,batch-report,WARN,Clock sync failed,req-82179030,trace-5297869651,unknown/invalid
1243,not-a-date,web-portal,WARN,Clock sync failed,req-14251180,trace-2529141801,unknown/invalid
1349,not-a-date,web-portal,WARN,Clock sync failed,req-62013608,NaN,unknown/invalid
1436,not-a-date,notification-worker,WARN,Clock sync failed,req-63214873,NaN,unknown/invalid
1486,not-a-date,web-portal,WARN,Clock sync failed,req-73453077,NaN,unknown/invalid
1665,not-a-date,web-portal,WARN,Clock sync failed,req-50946544,trace-7861474450,unknown/invalid
1771,not-a-date,batch-report,WARN,Clock sync failed,req-85371889,trace-3123961937,unknown/invalid
1779,not-a-date,notification-worker,WARN,Clock sync failed,req-74461050,trace-2996529219,unknown/invalid
1919,not-a-date,web-portal,WARN,Clock sync failed,req-70563375,trace-2561134894,unknown/invalid
2180,not-a-date,notification-worker,WARN,Clock sync failed,req-59574325,NaN,unknown/invalid
2188,not-a-date,payment-api,WARN,Clock sync failed,req-83681919,NaN,unknown/invalid
2297,not-a-date,web-portal,WARN,Clock sync failed,req-80176141,trace-9366141694,unknown/invalid
2675,not-a-date,batch-report,WARN,Clock sync failed,req-91884091,trace-3408843891,unknown/invalid

In [52]:
df_cleaned["timezone_offset"] = df_cleaned["timestamp"].str.extract(
    r"([+-]\d{2}:\d{2})$"
)

print(df_cleaned["timezone_offset"].value_counts())

timezone_offset
+07:00    590
Name: count, dtype: int64

In [53]:
display(df_cleaned[df_cleaned["timezone_offset"].notna()])

,timestamp,service,level,message,request_id,trace_id,timestamp_format,timezone_offset
119,2026-07-27T07:58:15+07:00,web-portal,INFO,Request completed path=/report in 554ms,req-20952896,NaN,ISO_timezone_offset,+07:00
125,2026-07-27T08:23:40+07:00,web-portal,INFO,Request completed path=/home in 752ms,req-70210270,NaN,ISO_timezone_offset,+07:00
126,2026-07-27T08:25:30+07:00,web-portal,INFO,Request completed path=/home in 489ms,req-31306555,NaN,ISO_timezone_offset,+07:00
133,2026-07-27T08:53:59+07:00,web-portal,INFO,Request completed path=/report in 768ms,req-48260510,NaN,ISO_timezone_offset,+07:00
137,2026-07-27T09:10:52+07:00,web-portal,INFO,Request completed path=/home in 535ms,req-91424562,NaN,ISO_timezone_offset,+07:00
...,...,...,...,...,...,...,...,...
2900,2026-08-03T06:15:30+07:00,web-portal,WARN,Response time 2100ms path=/report,req-45353565,trace-8774772376,ISO_timezone_offset,+07:00
2901,2026-08-03T06:30:10+07:00,web-portal,ERROR,ERR HTTP 502 upstream=payment-api path=/checkout,req-99609973,trace-7354458743,ISO_timezone_offset,+07:00
2902,2026-08-03T06:43:40+07:00,web-portal,INFO,Request completed path=/report in 284ms,req-87206285,trace-5698353763,ISO_timezone_offset,+07:00
2903,2026-08-03T06:55:40+07:00,web-portal,INFO,Request completed path=/home in 871ms,req-72913088,trace-5937414387,ISO_timezone_offset,+07:00
2904,2026-08-03T06:55:48+07:00,web-portal,INFO,Request completed path=/report in 109ms,req-61595935,trace-3995861929,ISO_timezone_offset,+07:00

Time range confirmation: 7 days from 27/07/2026 to 02/08/2026

In [54]:
df_cleaned['event_date_utc'] = pd.to_datetime(df_cleaned['timestamp'], utc=True, errors='coerce').dt.date
display(df_cleaned['event_date_utc'])

print(type(df_cleaned['event_date_utc'].iloc[0])) # first row

0       2026-07-27
1       2026-07-27
2       2026-07-27
3       2026-07-27
4       2026-07-27
           ...
2900    2026-08-02
2901    2026-08-02
2902    2026-08-02
2903    2026-08-02
2904    2026-08-02
Name: event_date_utc, Length: 2877, dtype: object

<class 'datetime.date'>

--- 
Let's go a bit deeper! (or I can say I'm doing: Root Cause Analysis)

In [55]:
not_a_date_df = df_cleaned[df_cleaned['timestamp'] == 'not-a-date'].copy()
not_a_date_df

,timestamp,service,level,message,request_id,trace_id,timestamp_format,timezone_offset,event_date_utc
33,not-a-date,auth-service,WARN,Clock sync failed,req-32170750,NaN,unknown/invalid,NaN,NaT
228,not-a-date,auth-service,WARN,Clock sync failed,req-80542438,trace-2840524582,unknown/invalid,NaN,NaT
483,not-a-date,auth-service,WARN,Clock sync failed,req-64770806,trace-3597287435,unknown/invalid,NaN,NaT
502,not-a-date,batch-report,WARN,Clock sync failed,req-89141563,trace-1842573576,unknown/invalid,NaN,NaT
553,not-a-date,notification-worker,WARN,Clock sync failed,req-95756894,trace-1839947796,unknown/invalid,NaN,NaT
696,not-a-date,payment-api,WARN,Clock sync failed,req-46941691,NaN,unknown/invalid,NaN,NaT
1029,not-a-date,batch-report,WARN,Clock sync failed,req-58571652,trace-8069263805,unknown/invalid,NaN,NaT
1191,not-a-date,batch-report,WARN,Clock sync failed,req-82179030,trace-5297869651,unknown/invalid,NaN,NaT
1243,not-a-date,web-portal,WARN,Clock sync failed,req-14251180,trace-2529141801,unknown/invalid,NaN,NaT
1349,not-a-date,web-portal,WARN,Clock sync failed,req-62013608,NaN,unknown/invalid,NaN,NaT
1436,not-a-date,notification-worker,WARN,Clock sync failed,req-63214873,NaN,unknown/invalid,NaN,NaT
1486,not-a-date,web-portal,WARN,Clock sync failed,req-73453077,NaN,unknown/invalid,NaN,NaT
1665,not-a-date,web-portal,WARN,Clock sync failed,req-50946544,trace-7861474450,unknown/invalid,NaN,NaT
1771,not-a-date,batch-report,WARN,Clock sync failed,req-85371889,trace-3123961937,unknown/invalid,NaN,NaT
1779,not-a-date,notification-worker,WARN,Clock sync failed,req-74461050,trace-2996529219,unknown/invalid,NaN,NaT
1919,not-a-date,web-portal,WARN,Clock sync failed,req-70563375,trace-2561134894,unknown/invalid,NaN,NaT
2180,not-a-date,notification-worker,WARN,Clock sync failed,req-59574325,NaN,unknown/invalid,NaN,NaT
2188,not-a-date,payment-api,WARN,Clock sync failed,req-83681919,NaN,unknown/invalid,NaN,NaT
2297,not-a-date,web-portal,WARN,Clock sync failed,req-80176141,trace-9366141694,unknown/invalid,NaN,NaT
2675,not-a-date,batch-report,WARN,Clock sync failed,req-91884091,trace-3408843891,unknown/invalid,NaN,NaT

- This reveals a critical pattern: **every single invalid record has the exact same message: "Clock sync failed"**
- The issue was spread across all 5 services (`auth-service`, `batch-report`, `notification-worker`, `payment-api`, and `web-portal`), meaning this is likely an underlying infrastructure or host-level issue rather than an isolated application bug

Applying **Data Imputation** technique: For `ffill` to be valid, the time gap between the record before the failure and the record after the failure must be narrow (e.g., milliseconds to a few seconds). If the gap is small, `ffill` introduces negligible error.

In [56]:
target_positions = [
    position
    for position, value in enumerate(df_cleaned["timestamp"])
    if value == "not-a-date"
]

context_positions = sorted({
    nearby_position
    for position in target_positions
    for nearby_position in range(
        max(0, position - 2),
        min(len(df_cleaned), position + 3),
    )
})

result = df_cleaned.iloc[context_positions].copy()
result["is_not_a_date"] = result["timestamp"].eq("not-a-date")

pd.set_option("display.max_rows", 100)
result

,timestamp,service,level,message,request_id,trace_id,timestamp_format,timezone_offset,event_date_utc,is_not_a_date
31,2026-07-27T02:43:27Z,payment-api,INFO,Payment processed txn=t919488 amount=250000,req-97219599,NaN,UTC_Z,NaN,2026-07-27,False
32,2026-07-27T02:44:22Z,auth-service,INFO,User login success uid=u3442,req-29876811,NaN,UTC_Z,NaN,2026-07-27,False
33,not-a-date,auth-service,WARN,Clock sync failed,req-32170750,NaN,unknown/invalid,NaN,NaT,True
34,2026-07-27T02:44:29Z,payment-api,INFO,Balance check ok uid=u3306,req-84801233,NaN,UTC_Z,NaN,2026-07-27,False
35,2026-07-27T02:49:58Z,notification-worker,WARN,Queue depth high depth=863,req-99929175,NaN,UTC_Z,NaN,2026-07-27,False
226,2026-07-27T13:54:41+07:00,web-portal,INFO,Request completed path=/report in 550ms,req-22086184,NaN,ISO_timezone_offset,+07:00,2026-07-27,False
227,2026-07-27T13:59:26+07:00,web-portal,INFO,Request completed path=/report in 119ms,req-78140959,NaN,ISO_timezone_offset,+07:00,2026-07-27,False
228,not-a-date,auth-service,WARN,Clock sync failed,req-80542438,trace-2840524582,unknown/invalid,NaN,NaT,True
229,2026-07-27T14:02:58Z,notification-worker,INFO,SMS sent uid=u2847,req-11619606,NaN,UTC_Z,NaN,2026-07-27,False
230,2026-07-27T14:08:30Z,batch-report,INFO,Daily report job started,req-59805178,NaN,UTC_Z,NaN,2026-07-27,False
481,2026-07-28T06:06:23Z,payment-api,INFO,Balance check ok uid=u6614,req-24572034,NaN,UTC_Z,NaN,2026-07-28,False
482,2026-07-28T06:12:36Z,payment-api,INFO,Balance check ok uid=u4594,req-34412077,NaN,UTC_Z,NaN,2026-07-28,False
483,not-a-date,auth-service,WARN,Clock sync failed,req-64770806,trace-3597287435,unknown/invalid,NaN,NaT,True
484,2026-07-28T06:13:59Z,notification-worker,INFO,SMS sent uid=u6629,req-87594146,NaN,UTC_Z,NaN,2026-07-28,False
485,2026-07-28T06:14:09Z,batch-report,INFO,Daily report job started,req-13891332,NaN,UTC_Z,NaN,2026-07-28,False
500,2026-07-28T07:05:25Z,payment-api,ERROR,ERR PaymentDeclined txn=t922041 code=51,req-58283485,NaN,UTC_Z,NaN,2026-07-28,False
501,2026-07-28T07:14:20+07:00,web-portal,WARN,Response time 2100ms path=/report,req-84311410,NaN,ISO_timezone_offset,+07:00,2026-07-28,False
502,not-a-date,batch-report,WARN,Clock sync failed,req-89141563,trace-1842573576,unknown/invalid,NaN,NaT,True
503,2026-07-28T07:22:02Z,payment-api,INFO,Payment processed txn=t628859 amount=990000,req-33813202,NaN,UTC_Z,NaN,2026-07-28,False
504,2026-07-28T07:26:12Z,notification-worker,ERROR,ERR SMTPConnRefused host=mail-gw,req-27720413,NaN,UTC_Z,NaN,2026-07-28,False
551,2026-07-28T11:13:27Z,batch-report,INFO,Daily report job started,req-41895802,NaN,UTC_Z,NaN,2026-07-28,False
552,2026-07-28T11:16:09Z,batch-report,INFO,Daily report job finished rows=867,req-10474177,NaN,UTC_Z,NaN,2026-07-28,False
553,not-a-date,notification-worker,WARN,Clock sync failed,req-95756894,trace-1839947796,unknown/invalid,NaN,NaT,True
554,2026-07-28T11:38:08Z,auth-service,INFO,Token refreshed uid=u3292,req-66178935,NaN,UTC_Z,NaN,2026-07-28,False
555,2026-07-28T11:40:03Z,notification-worker,WARN,Queue depth high depth=2027,req-56335527,NaN,UTC_Z,NaN,2026-07-28,False
694,2026-07-28T19:27:05+07:00,web-portal,INFO,Request completed path=/report in 527ms,req-87002404,NaN,ISO_timezone_offset,+07:00,2026-07-28,False
695,2026-07-28T19:31:47+07:00,web-portal,INFO,Request completed path=/report in 399ms,req-36703705,NaN,ISO_timezone_offset,+07:00,2026-07-28,False
696,not-a-date,payment-api,WARN,Clock sync failed,req-46941691,NaN,unknown/invalid,NaN,NaT,True
697,2026-08-01T01:47:50Z,payment-api,NaN,Heartbeat ok,req-21881015,trace-7088048157,UTC_Z,NaN,2026-08-01,False
698,2026-07-28T19:39:02Z,notification-worker,INFO,SMS sent uid=u9315,req-47101348,NaN,UTC_Z,NaN,2026-07-28,False
1027,2026-07-29T15:22:49+07:00,web-portal,WARN,Response time 2100ms path=/report,req-64888712,NaN,ISO_timezone_offset,+07:00,2026-07-29,False
1028,2026-07-29T15:23:46Z,auth-service,ERROR,ERR AuthTokenExpired uid=u4571,req-68985391,NaN,UTC_Z,NaN,2026-07-29,False
1029,not-a-date,batch-report,WARN,Clock sync failed,req-58571652,trace-8069263805,unknown/invalid,NaN,NaT,True
1030,2026-07-29T15:26:19Z,batch-report,INFO,Daily report job finished rows=985,req-99345471,NaN,UTC_Z,NaN,2026-07-29,False
1031,2026-07-29T15:27:46Z,auth-service,INFO,User login success uid=u9177,req-57794571,NaN,UTC_Z,NaN,2026-07-29,False
1189,2026-07-30T04:46:03+07:00,web-portal,INFO,Request completed path=/report in 399ms,req-78495121,NaN,ISO_timezone_offset,+07:00,2026-07-29,False
1190,2026-07-30T05:09:54+07:00,web-portal,INFO,Request completed path=/home in 728ms,req-75629343,NaN,ISO_timezone_offset,+07:00,2026-07-29,False
1191,not-a-date,batch-report,WARN,Clock sync failed,req-82179030,trace-5297869651,unknown/invalid,NaN,NaT,True
1192,2026-07-30T06:29:10+07:00,web-portal,WARN,Response time 2100ms path=/report,req-60181152,NaN,ISO_timezone_offset,+07:00,2026-07-29,False
1193,2026-07-30T00:01:24Z,payment-api,INFO,Balance check ok uid=u1817,req-99298543,NaN,UTC_Z,NaN,2026-07-30,False
1241,2026-07-30T02:24:13Z,notification-worker,ERROR,ERR SMTPConnRefused host=mail-gw,req-33517361,NaN,UTC_Z,NaN,2026-07-30,False
1242,2026-07-30T02:31:18Z,batch-report,INFO,Daily report job finished rows=906,req-31916266,NaN,UTC_Z,NaN,2026-07-30,False
1243,not-a-date,web-portal,WARN,Clock sync failed,req-14251180,trace-2529141801,unknown/invalid,NaN,NaT,True
1244,2026-07-30T02:38:41Z,payment-api,INFO,Payment processed txn=t788866 amount=250000,req-26415312,NaN,UTC_Z,NaN,2026-07-30,False
1245,2026-07-30T02:39:23Z,notification-worker,INFO,SMS sent uid=u4335,req-16071188,NaN,UTC_Z,NaN,2026-07-30,False
1347,2026-07-30T07:52:31Z,payment-api,INFO,Payment processed txn=t220364 amount=120000,req-21199497,NaN,UTC_Z,NaN,2026-07-30,False
1348,2026-07-30T07:54:25Z,notification-worker,WARN,Queue depth high depth=2619,req-67953043,NaN,UTC_Z,NaN,2026-07-30,False
1349,not-a-date,web-portal,WARN,Clock sync failed,req-62013608,NaN,unknown/invalid,NaN,NaT,True
1350,2026-07-30T07:57:35Z,auth-service,INFO,User login success uid=u4074,req-38153923,NaN,UTC_Z,NaN,2026-07-30,False
1351,2026-07-30T08:03:27Z,payment-api,ERROR,ERR ConnTimeout db-primary after 30s retry=3,req-27342988,NaN,UTC_Z,NaN,2026-07-30,False
1434,2026-07-30T11:57:53Z,batch-report,INFO,Daily report job finished rows=867,req-60300871,NaN,UTC_Z,NaN,2026-07-30,False
1435,2026-07-30T11:59:25Z,payment-api,INFO,Balance check ok uid=u7218,req-26950183,NaN,UTC_Z,NaN,2026-07-30,False
1436,not-a-date,notification-worker,WARN,Clock sync failed,req-63214873,NaN,unknown/invalid,NaN,NaT,True
1437,2026-07-30T12:05:52+07:00,web-portal,WARN,Response time 2100ms path=/report,req-85636982,NaN,ISO_timezone_offset,+07:00,2026-07-30,False
1438,2026-07-30T12:06:12Z,payment-api,ERROR,ERR ConnTimeout db-primary after 30s retry=3,req-75741381,NaN,UTC_Z,NaN,2026-07-30,False
1484,2026-07-30T14:50:21Z,notification-worker,INFO,SMS sent uid=u7247,req-51767937,NaN,UTC_Z,NaN,2026-07-30,False
1485,2026-07-30T14:50:27Z,payment-api,ERROR,ERR ConnTimeout db-primary after 30s retry=3,req-25832863,NaN,UTC_Z,NaN,2026-07-30,False
1486,not-a-date,web-portal,WARN,Clock sync failed,req-73453077,NaN,unknown/invalid,NaN,NaT,True
1487,2026-07-30T14:50:32Z,batch-report,INFO,Daily report job started,req-32782148,NaN,UTC_Z,NaN,2026-07-30,False
1488,2026-07-30T14:55:29Z,payment-api,ERROR,ERR ConnTimeout db-primary after 30s retry=3,req-97688458,NaN,UTC_Z,NaN,2026-07-30,False
1663,2026-07-30T22:42:42Z,payment-api,INFO,Balance check ok uid=u3664,req-12092776,NaN,UTC_Z,NaN,2026-07-30,False
1664,2026-07-30T22:42:46Z,auth-service,WARN,Slow login 900ms uid=u9924,req-99618537,NaN,UTC_Z,NaN,2026-07-30,False
1665,not-a-date,web-portal,WARN,Clock sync failed,req-50946544,trace-7861474450,unknown/invalid,NaN,NaT,True
1666,2026-07-30T22:46:51+07:00,web-portal,INFO,Request completed path=/home in 624ms,req-82364511,NaN,ISO_timezone_offset,+07:00,2026-07-30,False
1667,2026-07-30T22:47:20Z,batch-report,INFO,Daily report job finished rows=803,req-73150290,NaN,UTC_Z,NaN,2026-07-30,False
1769,2026-07-31T03:07:53Z,batch-report,WARN,Report row mismatch expected=845 got=866,req-70891460,trace-5756773490,UTC_Z,NaN,2026-07-31,False
1770,2026-07-31T03:08:16Z,batch-report,INFO,Daily report job started,req-70033217,trace-5024636765,UTC_Z,NaN,2026-07-31,False
1771,not-a-date,batch-report,WARN,Clock sync failed,req-85371889,trace-3123961937,unknown/invalid,NaN,NaT,True
1772,2026-07-31T03:24:14Z,batch-report,INFO,Daily report job finished rows=1008,req-39075869,trace-9654071754,UTC_Z,NaN,2026-07-31,False
1773,2026-07-31T03:28:48Z,auth-service,INFO,Session created uid=u7293,req-75892915,trace-8420959730,UTC_Z,NaN,2026-07-31,False
1777,2026-07-31T03:43:22Z,auth-service,INFO,User login success uid=u9565,req-55386805,trace-5643541357,UTC_Z,NaN,2026-07-31,False
1778,2026-07-31T03:54:18Z,auth-service,INFO,Session created uid=u1004,req-46806704,trace-4995004351,UTC_Z,NaN,2026-07-31,False
1779,not-a-date,notification-worker,WARN,Clock sync failed,req-74461050,trace-2996529219,unknown/invalid,NaN,NaT,True
1780,2026-07-31T03:54:45Z,payment-api,INFO,Balance check ok uid=u9986,req-37500238,trace-1257182161,UTC_Z,NaN,2026-07-31,False
1781,2026-07-31T04:06:18Z,payment-api,INFO,Payment processed txn=t798258 amount=250000,req-28396122,trace-1917237744,UTC_Z,NaN,2026-07-31,False
1917,2026-07-31T13:38:10Z,batch-report,INFO,Daily report job finished rows=1001,req-62890778,trace-1842274225,UTC_Z,NaN,2026-07-31,False
1918,2026-07-31T13:42:36Z,payment-api,INFO,Payment processed txn=t103425 amount=50000,req-71036929,trace-8821815074,UTC_Z,NaN,2026-07-31,False
1919,not-a-date,web-portal,WARN,Clock sync failed,req-70563375,trace-2561134894,unknown/invalid,NaN,NaT,True
1920,2026-07-31T13:44:25+07:00,web-portal,INFO,Request completed path=/home in 521ms,req-32732400,trace-2751962237,ISO_timezone_offset,+07:00,2026-07-31,False
1921,2026-07-31T13:44:29Z,auth-service,INFO,Token refreshed uid=u1489,req-11780943,trace-9779057924,UTC_Z,NaN,2026-07-31,False
2178,2026-08-01T05:00:26Z,auth-service,INFO,Token refreshed uid=u5158,req-82537571,trace-2085051459,UTC_Z,NaN,2026-08-01,False
2179,2026-08-01T05:00:35Z,notification-worker,INFO,SMS sent uid=u8667,req-65767703,trace-5749304490,UTC_Z,NaN,2026-08-01,False
2180,not-a-date,notification-worker,WARN,Clock sync failed,req-59574325,NaN,unknown/invalid,NaN,NaT,True
2181,2026-08-01T05:02:15Z,batch-report,INFO,Daily report job started,req-85900715,trace-5992932347,UTC_Z,NaN,2026-08-01,False
2182,2026-08-01T05:04:15Z,notification-worker,INFO,Email sent uid=u9832,req-69960207,trace-8589455936,UTC_Z,NaN,2026-08-01,False
2186,2026-08-01T05:18:09Z,auth-service,INFO,Token refreshed uid=u4224,req-30691518,trace-9524331050,UTC_Z,NaN,2026-08-01,False
2187,2026-08-01T05:26:07Z,notification-worker,INFO,Email sent uid=u7407,req-76690193,trace-5878838809,UTC_Z,NaN,2026-08-01,False
2188,not-a-date,payment-api,WARN,Clock sync failed,req-83681919,NaN,unknown/invalid,NaN,NaT,True
2189,2026-08-01T05:38:05Z,notification-worker,ERROR,ERR SMTPConnRefused host=mail-gw,req-71989770,trace-1690528328,UTC_Z,NaN,2026-08-01,False
2190,2026-08-01T05:39:40Z,payment-api,INFO,Payment processed txn=t364201 amount=50000,req-97890289,trace-1471184735,UTC_Z,NaN,2026-08-01,False
2295,2026-08-01T12:39:48+07:00,web-portal,INFO,Request completed path=/home in 861ms,req-61711055,trace-7587519811,ISO_timezone_offset,+07:00,2026-08-01,False
2296,2026-08-01T12:41:42Z,batch-report,ERROR,ERR NullPointer in ReportBuilder step=aggregate,req-41224916,trace-4841584895,UTC_Z,NaN,2026-08-01,False
2297,not-a-date,web-portal,WARN,Clock sync failed,req-80176141,trace-9366141694,unknown/invalid,NaN,NaT,True
2298,2026-08-01T12:44:27Z,batch-report,INFO,Daily report job finished rows=1174,req-60582687,trace-9031063171,UTC_Z,NaN,2026-08-01,False
2299,2026-08-01T12:44:29+07:00,web-portal,INFO,Request completed path=/home in 172ms,req-25454302,trace-8990448505,ISO_timezone_offset,+07:00,2026-08-01,False
2673,2026-08-02T10:30:31+07:00,web-portal,INFO,Request completed path=/home in 522ms,req-71777181,trace-5074288018,ISO_timezone_offset,+07:00,2026-08-02,False
2674,2026-08-02T10:31:13Z,auth-service,INFO,User login success uid=u5394,req-60304388,trace-3485002985,UTC_Z,NaN,2026-08-02,False
2675,not-a-date,batch-report,WARN,Clock sync failed,req-91884091,trace-3408843891,unknown/invalid,NaN,NaT,True
2676,2026-08-02T10:36:08Z,auth-service,INFO,User login success uid=u4248,req-47535728,trace-8766760796,UTC_Z,NaN,2026-08-02,False
2677,2026-08-02T10:38:10Z,batch-report,INFO,Daily report job finished rows=1144,req-83914229,trace-1962916168,UTC_Z,NaN,2026-08-02,False

In [70]:
expected_corrupted = (df['timestamp'] == "not-a-date")
expected_corrupted

0       False
1       False
2       False
3       False
4       False
        ...
2900    False
2901    False
2902    False
2903    False
2904    False
Name: timestamp, Length: 2905, dtype: bool

## 2. service

In [57]:
df_cleaned['service'].unique()

<StringArray>
['notification-worker',        'auth-service',         'payment-api',
        'batch-report',          'web-portal']
Length: 5, dtype: str

## 3. level

In [58]:
df_cleaned['level'].unique()

<StringArray>
['ERROR', 'INFO', 'WARN', nan]
Length: 4, dtype: str

18 missing values out of 2905 records

In [59]:
df_cleaned[df_cleaned['level'].isna()]

,timestamp,service,level,message,request_id,trace_id,timestamp_format,timezone_offset,event_date_utc
10,2026-07-30T12:07:36Z,notification-worker,NaN,Heartbeat ok,req-48936328,NaN,UTC_Z,NaN,2026-07-30
94,2026-07-30T18:23:58Z,payment-api,NaN,Heartbeat ok,req-30906603,NaN,UTC_Z,NaN,2026-07-30
213,2026-07-30T13:53:09Z,payment-api,NaN,Heartbeat ok,req-89098923,NaN,UTC_Z,NaN,2026-07-30
300,2026-07-31T18:38:08Z,auth-service,NaN,Heartbeat ok,req-18963036,trace-4082960786,UTC_Z,NaN,2026-07-31
697,2026-08-01T01:47:50Z,payment-api,NaN,Heartbeat ok,req-21881015,trace-7088048157,UTC_Z,NaN,2026-08-01
703,2026-08-01T07:53:41+07:00,web-portal,NaN,Heartbeat ok,req-71725422,trace-9264884678,ISO_timezone_offset,+07:00,2026-08-01
830,2026-08-02T01:19:22Z,auth-service,NaN,Heartbeat ok,req-11122998,trace-7153186561,UTC_Z,NaN,2026-08-02
1038,2026-07-29T03:14:59Z,batch-report,NaN,Heartbeat ok,req-22252693,NaN,UTC_Z,NaN,2026-07-29
1277,2026-07-28T18:01:01Z,auth-service,NaN,Heartbeat ok,req-29057175,NaN,UTC_Z,NaN,2026-07-28
1316,2026-07-27T23:43:39Z,batch-report,NaN,Heartbeat ok,req-41470269,NaN,UTC_Z,NaN,2026-07-27
1552,2026-07-27T23:57:02Z,auth-service,NaN,Heartbeat ok,req-99461443,NaN,UTC_Z,NaN,2026-07-27
1675,2026-07-31T22:31:38Z,batch-report,NaN,Heartbeat ok,req-51396067,trace-6294752013,UTC_Z,NaN,2026-07-31
1838,2026-07-31T06:42:07Z,payment-api,NaN,Heartbeat ok,req-11502307,trace-3954020838,UTC_Z,NaN,2026-07-31
1967,2026-08-02T06:34:47+07:00,web-portal,NaN,Heartbeat ok,req-23192745,trace-7481479796,ISO_timezone_offset,+07:00,2026-08-01
2043,2026-08-02T11:38:14Z,auth-service,NaN,Heartbeat ok,req-37980569,trace-4538630049,UTC_Z,NaN,2026-08-02
2167,2026-07-31T21:25:54Z,notification-worker,NaN,Heartbeat ok,req-51570260,trace-1192650241,UTC_Z,NaN,2026-07-31
2555,2026-08-01T12:13:50Z,payment-api,NaN,Heartbeat ok,req-93885180,trace-3933217062,UTC_Z,NaN,2026-08-01
2728,2026-07-30T23:57:51Z,payment-api,NaN,Heartbeat ok,req-80593774,NaN,UTC_Z,NaN,2026-07-30

## 4. message

In [60]:
df_cleaned['message'].unique()

<StringArray>
[        'ERR SMTPConnRefused host=mail-gw',
                'Session created uid=u2746',
    'Retry 1/3 calling notification-worker',
                       'SMS sent uid=u1132',
               'Slow login 900ms uid=u7882',
                'Session created uid=u2528',
                     'Email sent uid=u2106',
                 'Daily report job started',
 'Report row mismatch expected=843 got=759',
                       'SMS sent uid=u5942',
 ...
  'Request completed path=/report in 167ms',
  'Request completed path=/report in 643ms',
    'Request completed path=/home in 753ms',
    'Request completed path=/home in 178ms',
  'Request completed path=/report in 332ms',
    'Request completed path=/home in 795ms',
    'Request completed path=/home in 868ms',
  'Request completed path=/report in 284ms',
    'Request completed path=/home in 871ms',
  'Request completed path=/report in 109ms']
Length: 2153, dtype: str

High cardinality: 2,153 distinct strings / 2,905 rows, because messages embed dynamic values such as user IDs, transaction IDs, amounts, paths, latency, row counts, etc

---

Deep dive in ERROR rows

In [61]:
df_cleaned[df_cleaned['level'] == 'ERROR']['message'].unique()

<StringArray>
[                'ERR SMTPConnRefused host=mail-gw',
     'ERR ConnTimeout db-primary after 30s retry=3',
          'ERR PaymentDeclined txn=t811163 code=51',
  'ERR NullPointer in ReportBuilder step=aggregate',
                   'ERR AuthTokenExpired uid=u6576',
          'ERR PaymentDeclined txn=t108105 code=51',
 'ERR HTTP 502 upstream=payment-api path=/checkout',
          'ERR PaymentDeclined txn=t534303 code=51',
                   'ERR AuthTokenExpired uid=u7209',
          'ERR PaymentDeclined txn=t108060 code=51',
                   'ERR AuthTokenExpired uid=u6592',
          'ERR PaymentDeclined txn=t922041 code=51',
                   'ERR AuthTokenExpired uid=u8751',
          'ERR PaymentDeclined txn=t642892 code=51',
                   'ERR AuthTokenExpired uid=u1587',
                   'ERR AuthTokenExpired uid=u8324',
                   'ERR AuthTokenExpired uid=u4389',
                   'ERR AuthTokenExpired uid=u5550',
                   'ERR AuthTokenExpired uid=u1916',
                   'ERR AuthTokenExpired uid=u3235',
          'ERR PaymentDeclined txn=t251357 code=51',
                   'ERR AuthTokenExpired uid=u4571',
                   'ERR AuthTokenExpired uid=u1326',
                   'ERR AuthTokenExpired uid=u2478',
          'ERR PaymentDeclined txn=t962813 code=51',
          'ERR PaymentDeclined txn=t916656 code=51',
                   'ERR AuthTokenExpired uid=u1570',
                   'ERR AuthTokenExpired uid=u2479',
                   'ERR AuthTokenExpired uid=u5505',
          'ERR PaymentDeclined txn=t233465 code=51',
          'ERR PaymentDeclined txn=t687712 code=51',
                   'ERR AuthTokenExpired uid=u4927',
          'ERR PaymentDeclined txn=t940208 code=51',
          'ERR PaymentDeclined txn=t342106 code=51',
          'ERR PaymentDeclined txn=t894036 code=51',
          'ERR PaymentDeclined txn=t362073 code=51',
                   'ERR AuthTokenExpired uid=u1166',
                   'ERR AuthTokenExpired uid=u3010',
          'ERR PaymentDeclined txn=t752126 code=51',
                   'ERR AuthTokenExpired uid=u2250',
                   'ERR AuthTokenExpired uid=u6921',
          'ERR PaymentDeclined txn=t595043 code=51',
          'ERR PaymentDeclined txn=t342928 code=51',
                   'ERR AuthTokenExpired uid=u9225',
          'ERR PaymentDeclined txn=t538272 code=51',
                   'ERR AuthTokenExpired uid=u8392',
                   'ERR AuthTokenExpired uid=u9046',
                   'ERR AuthTokenExpired uid=u5545',
          'ERR PaymentDeclined txn=t433888 code=51',
                   'ERR AuthTokenExpired uid=u1788',
                   'ERR AuthTokenExpired uid=u8597',
          'ERR PaymentDeclined txn=t967878 code=51',
                   'ERR AuthTokenExpired uid=u2818',
          'ERR PaymentDeclined txn=t698643 code=51',
                   'ERR AuthTokenExpired uid=u6567',
                   'ERR AuthTokenExpired uid=u6880',
                   'ERR AuthTokenExpired uid=u4241',
                   'ERR AuthTokenExpired uid=u1674',
                   'ERR AuthTokenExpired uid=u9206',
                   'ERR AuthTokenExpired uid=u6263',
          'ERR PaymentDeclined txn=t754148 code=51',
          'ERR PaymentDeclined txn=t555053 code=51',
                   'ERR AuthTokenExpired uid=u3756',
          'ERR PaymentDeclined txn=t829928 code=51']
Length: 64, dtype: str

Only ERROR logs have messages starting with the keyword 'ERR'

In [66]:
df_cleaned[
    df_cleaned['level'] != 'ERROR']

,timestamp,service,level,message,request_id,trace_id,timestamp_format,timezone_offset,event_date_utc,error_type
1,2026-07-27T00:12:06Z,auth-service,INFO,Session created uid=u2746,req-72350830,NaN,UTC_Z,NaN,2026-07-27,NaN
2,2026-07-27T00:13:20Z,payment-api,WARN,Retry 1/3 calling notification-worker,req-22315507,NaN,UTC_Z,NaN,2026-07-27,NaN
3,2026-07-27T00:20:17Z,notification-worker,INFO,SMS sent uid=u1132,req-27740248,NaN,UTC_Z,NaN,2026-07-27,NaN
4,2026-07-27T00:27:38Z,auth-service,WARN,Slow login 900ms uid=u7882,req-95306788,NaN,UTC_Z,NaN,2026-07-27,NaN
5,2026-07-27T00:32:14Z,auth-service,INFO,Session created uid=u2528,req-38688676,NaN,UTC_Z,NaN,2026-07-27,NaN
...,...,...,...,...,...,...,...,...,...,...
2899,2026-08-03T06:06:45+07:00,web-portal,INFO,Request completed path=/home in 868ms,req-17243541,trace-5560561097,ISO_timezone_offset,+07:00,2026-08-02,NaN
2900,2026-08-03T06:15:30+07:00,web-portal,WARN,Response time 2100ms path=/report,req-45353565,trace-8774772376,ISO_timezone_offset,+07:00,2026-08-02,NaN
2902,2026-08-03T06:43:40+07:00,web-portal,INFO,Request completed path=/report in 284ms,req-87206285,trace-5698353763,ISO_timezone_offset,+07:00,2026-08-02,NaN
2903,2026-08-03T06:55:40+07:00,web-portal,INFO,Request completed path=/home in 871ms,req-72913088,trace-5937414387,ISO_timezone_offset,+07:00,2026-08-02,NaN
2904,2026-08-03T06:55:48+07:00,web-portal,INFO,Request completed path=/report in 109ms,req-61595935,trace-3995861929,ISO_timezone_offset,+07:00,2026-08-02,NaN

## 5. request_id

In [ ]:
df_cleaned['request_id'].head(10)

Check to see all match `req-########`

In [ ]:
pattern = r"req-\d{8}"

# Rows that do not match the pattern
df_cleaned[~df_cleaned['request_id'].str.fullmatch(pattern, na=False)]

In [ ]:
duplicated_request_df = df_cleaned[df_cleaned.duplicated(subset=['request_id'], keep='first')]
display(duplicated_request_df)

print(len(duplicated_request_df), "duplicated request_id records found.")

## 6. trace_id

In [ ]:
len(df_cleaned)

In [ ]:
df_cleaned[~df_cleaned['trace_id'].isna()]

In [ ]:
pattern = r"trace-\d{10}"

# Rows that do not match the pattern (exclude NaN values)
df_cleaned[~df_cleaned['trace_id'].str.fullmatch(pattern, na=True)]

Let's check when the `trace_id` starts existing

In [ ]:
missing_trace_df = df_cleaned[df_cleaned['trace_id'].isna()]
missing_trace_df[missing_trace_df['event_date_utc'].notna()].sort_values(by='event_date_utc', ascending=True)

In [ ]:
non_missing_trace_df = df_cleaned[df_cleaned['trace_id'].notna() & df_cleaned['event_date_utc'].notna()]
non_missing_trace_df.sort_values(by='event_date_utc', ascending=True)

The missingness is highly structured: for valid timestamps, events on Jul 27–30 have no trace ID, while Jul 31–Aug 2 have one, suggesting a source/schema evolution rather than random bad data. Here are some duplicated trace IDs

In [ ]:
dup_non_missing_trace_df = non_missing_trace_df[non_missing_trace_df.duplicated(subset=['trace_id'], keep=False)]
display(dup_non_missing_trace_df)

print(len(dup_non_missing_trace_df), "duplicated trace_id records found.")